package com.moraydata.general.management.repository;

import java.util.HashSet;
import java.util.Properties;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.jpa.repository.support.EntityManagerBeanDefinitionRegistrarPostProcessor;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;
import org.springframework.transaction.PlatformTransactionManager;

import com.moraydata.general.management.util.SpringUtils;

import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public abstract class BaseJpaRepositoryConfiguration {
	
	/**
	 * The name of bean which named SharedEntityManagerCreator#Index
	 * and generated by {@link EntityManagerBeanDefinitionRegistrarPostProcessor}
	 * will be collected in this set.
	 * This will be used to remove the bean definition of beans from Spring bean container.
	 * @see com.beamofsoul.rabbit.management.system.SystemStartupRunner#run(String...)
	 * 
	 * The default initial capacity of HashSet is 16, so to minimize possible capacity,
	 * just set its' initial capacity is 4 for current case.
	 */
	public static Set<String> sharedEntityManagerCreatorNameSet = new HashSet<>(4);
	
	@Value("${spring.jpa.generate-ddl}")
	Boolean generateDdl;
	
	@Value("${spring.jpa.show-sql}")
    String showSql;
	
	@Value("${spring.jpa.hibernate.format-sql}")
	String formatSql;
	
	@Value("${spring.jpa.hibernate.use_sql_comments}")
	String useSqlComments;
    
    @Value("${spring.jpa.properties.hibernate.dialect}")
    String dialect;
    
    @Value("${spring.jpa.hibernate.use-new-id-generator-mappings}")
    String useNewIdGeneratorMappings;
    
    @Value("${spring.jpa.hibernate.ddl-auto}")
    String ddlAuto;
    
    @Value("${spring.jpa.hibernate.naming.physical-strategy}")
    String physicalStrategy;
    
    @Value("${spring.jpa.hibernate.naming.implicit-strategy}")
    String implicitStrategy;
    
    BaseJpaRepositoryConfiguration() {
    	log.info(this.getClass().getName());
    }

	boolean getGeneratDdlStrategy() {
		return this.generateDdl; 
	}

	HibernateJpaVendorAdapter getHibernateJpaVendorAdapter() {
		HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
		vendorAdapter.setGenerateDdl(getGeneratDdlStrategy());
		return vendorAdapter;
	}

	Properties getProperties() {
		Properties properties = new Properties();
		properties.setProperty("hibernate.show_sql", showSql);
		properties.setProperty("hibernate.format_sql", formatSql);
		properties.setProperty("hibernate.use_sql_comments", useSqlComments);
		properties.setProperty("hibernate.dialect", dialect);
		properties.setProperty("hibernate.hbm2ddl.auto", ddlAuto);
		properties.setProperty("hibernate.id.new_generator_mappings", useNewIdGeneratorMappings);
		properties.setProperty("hibernate.implicit_naming_strategy", implicitStrategy);
		properties.setProperty("hibernate.physical_naming_strategy", physicalStrategy);
		return properties;
	}
	
	LocalContainerEntityManagerFactoryBean getEntityManagerFactory(final DataSource dataSource, final String entityPackagePath2Scan, final String persistenceUnitName) {
		LocalContainerEntityManagerFactoryBean factoryBean = new LocalContainerEntityManagerFactoryBean();
		factoryBean.setPersistenceUnitName(persistenceUnitName);
		factoryBean.setJpaVendorAdapter(getHibernateJpaVendorAdapter());
		factoryBean.setPackagesToScan(entityPackagePath2Scan);
		factoryBean.setDataSource(dataSource);
		factoryBean.setJpaProperties(getProperties());
		factoryBean.afterPropertiesSet();
		return factoryBean;
	}
	
	/**
	 * @deprecated recommended to use generated sharedEntityManagerCreator by {@link EntityManagerBeanDefinitionRegistrarPostProcessor} 
	 * @param entityManagerFactory
	 * @return a new EntityManager instance
	 */
	@Deprecated
	EntityManager getEntityManager(@NonNull LocalContainerEntityManagerFactoryBean entityManagerFactory) {
		return entityManagerFactory.getObject().createEntityManager();
	}
	
	public abstract LocalContainerEntityManagerFactoryBean entityManagerFactory();
	
	PlatformTransactionManager getTransactionManager() {
		return new JpaTransactionManager(entityManagerFactory().getObject());
	}
	
	/**
	 * Remove all {@link org.springframework.orm.jpa.SharedEntityManagerCreator}
	 * bean definitions in Spring bean container.
	 */
	public static void removeGeneratedSharedEntityManagerCreatorBeanDefinitions() {
		for (String beanName : sharedEntityManagerCreatorNameSet) {
			SpringUtils.removeBean(beanName);
		}
	}
}
